export const ROUTES = {
  home: "/",
  login: "/auth/login",
  signup: "/auth/signup",
  chooseProfile: "/auth/choose-profile",
  patientDashboard: "/patient/dashboard",
  patientRecords: "/patient/records",
  patientPermissions: "/patient/permissions",
  patientProfile: "/patient/profile",
  doctorDashboard: "/doctor/dashboard",
  doctorPatients: "/doctor/patients",
  doctorRecords: "/doctor/records",
  doctorProfile: "/doctor/profile",
  clinicDashboard: "/clinic/dashboard",
  clinicPatients: "/clinic/patients",
  clinicDoctors: "/clinic/doctors",
  clinicRecords: "/clinic/records",
  clinicSettings: "/clinic/settings",
  chainlinkVerification: "/verification/chainlink",
  recordVerification: "/verification/record",
} as const;
